# Объединение датафреймов

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
os.chdir('/content/drive/MyDrive/SkillBox/Pandas')

In [3]:
ls -l

total 1977
-rw------- 1 root root 578365 Jul 19 14:14 '12.1 Pandas.pdf'
-rw------- 1 root root  84562 Jul 20 14:04  12.1_SkillBox_Pandas.ipynb
-rw------- 1 root root  51339 Jul 20 14:32  12.1_SkillBox_Pandas_Практика.ipynb
drwx------ 2 root root   4096 Jul 20 12:19  12.2.Data/
-rw------- 1 root root  63132 Jul 21 23:02  12.2_Чтение_файлов_в_Pandas_Практика.ipynb
-rw------- 1 root root 214508 Jul 21 22:19  12.2_Чтение_файлов_с_помощью_Pandas.ipynb
-rw------- 1 root root 460387 Jul 20 08:23 '12.2 Чтение файлов с помощью Pandas.pdf'
drwx------ 2 root root   4096 Jul 24 06:29  12.3.Data/
-rw------- 1 root root 310314 Jul 24 06:39  12.3_SkillBox_JSON-файлы.ipynb
-rw------- 1 root root  96534 Jul 24 07:34  12.3_SkillBox_JSON-файлы_Практика.ipynb
-rw------- 1 root root  83432 Jul 24 07:41  12.4_SkillBox_Подсчёт_простых_статистик_в_Pandas.ipynb
drwx------ 2 root root   4096 Jul 24 07:46  12.5.Data/
-rw------- 1 root root  66924 Jul 24 07:50  12.5_SkillBox_Объединение_датафреймов.ipynb

In [4]:
import pandas as pd

In [5]:
pd_df = pd.read_csv('12.5.Data/partner_data.csv')
pd_df.head()

   id   age          job  marital  education  balance housing loan default
0   1  26.0   unemployed  married   tertiary      454     yes  yes      no
1   2  25.0   technician  married  secondary      517      no   no      no
2   3  36.0   technician   single  secondary     1044     yes   no      no
3   4  45.0  blue-collar  married  secondary      146     yes  yes      no
4   5  27.0   management  married   tertiary      145      no   no      no

In [6]:
pdnp_df = pd.read_csv('12.5.Data/partner_data_next_part.csv')
pdnp_df.head()

     id          job   marital  education  balance housing loan default
0  1001   technician       NaN   tertiary        0      no   no     yes
1  1002  blue-collar   married    primary      300     yes   no      no
2  1003   management   married   tertiary       15     yes   no      no
3  1004  blue-collar    single    primary     -100     yes   no      no
4  1005     services  divorced  secondary      430     yes  yes     yes

In [7]:
pdnp_df.shape

(10, 8)

In [8]:
# присоединение строк снизу
# data_frame1 append (data_frame2)
full_df = pd_df.append(pdnp_df)
full_df

<ipython-input-8-2b855ce66891>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  full_df = pd_df.append(pdnp_df)

,id,age,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2,25.0,technician,married,secondary,517,no,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
5,1006,NaN,management,married,tertiary,2071,yes,no,no
6,1007,NaN,entrepreneur,married,secondary,-1882,no,no,no
7,1008,NaN,unknown,single,unknown,1819,no,no,no
8,1009,NaN,self-employed,NaN,secondary,146,yes,no,no
9,1010,NaN,services,single,secondary,297,no,no,no

In [9]:
full_df.tail(15)

,id,age,job,marital,education,balance,housing,loan,default
995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no
996,997,58.0,management,married,tertiary,1271,yes,no,no
997,998,31.0,services,single,secondary,297,no,no,no
998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no
999,1000,23.0,blue-collar,single,secondary,780,yes,no,no
0,1001,NaN,technician,NaN,tertiary,0,no,no,yes
1,1002,NaN,blue-collar,married,primary,300,yes,no,no
2,1003,NaN,management,married,tertiary,15,yes,no,no
3,1004,NaN,blue-collar,single,primary,-100,yes,no,no
4,1005,NaN,services,divorced,secondary,430,yes,yes,yes
5,1006,NaN,management,married,tertiary,2071,yes,no,no
6,1007,NaN,entrepreneur,married,secondary,-1882,no,no,no
7,1008,NaN,unknown,single,unknown,1819,no,no,no
8,1009,NaN,self-employed,NaN,secondary,146,yes,no,no
9,1010,NaN,services,single,secondary,297,no,no,no

In [13]:
# присоединение строк снизу
# data_frame1 append (data_frame2)
pd.concat([pd_df, pdnp_df], axis=0)

,id,age,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2,25.0,technician,married,secondary,517,no,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
5,1006,NaN,management,married,tertiary,2071,yes,no,no
6,1007,NaN,entrepreneur,married,secondary,-1882,no,no,no
7,1008,NaN,unknown,single,unknown,1819,no,no,no
8,1009,NaN,self-employed,NaN,secondary,146,yes,no,no
9,1010,NaN,services,single,secondary,297,no,no,no

In [11]:
# присоединение строк справа
# pd.concat ([data_frame1, data_frame2], axis=1)
pd.concat([pd_df, pdnp_df], axis=1)

,id,age,job,marital,education,balance,housing,loan,default,id,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no,1001.0,technician,NaN,tertiary,0.0,no,no,yes
1,2,25.0,technician,married,secondary,517,no,no,no,1002.0,blue-collar,married,primary,300.0,yes,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no,1003.0,management,married,tertiary,15.0,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no,1004.0,blue-collar,single,primary,-100.0,yes,no,no
4,5,27.0,management,married,tertiary,145,no,no,no,1005.0,services,divorced,secondary,430.0,yes,yes,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,997,58.0,management,married,tertiary,1271,yes,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,998,31.0,services,single,secondary,297,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,1000,23.0,blue-collar,single,secondary,780,yes,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
opd_df = pd.read_csv('12.5.Data/other_partner_data.csv')
opd_df.head()

   id gender
0   1  women
1   2  women
2   3    man
3   5    man
4   6    man

In [16]:
opd_df['gender'].describe()

count     710
unique      2
top       man
freq      439
Name: gender, dtype: object

In [17]:
print(sorted(opd_df['id'].values))

[1, 2, 3, 5, 6, 7, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 26, 28, 29, 30, 31, 33, 34, 36, 37, 38, 39, 40, 43, 47, 48, 49, 50, 51, 52, 54, 55, 57, 58, 59, 61, 63, 65, 66, 68, 70, 71, 72, 73, 74, 76, 81, 82, 83, 85, 87, 88, 90, 91, 92, 93, 94, 96, 99, 100, 102, 103, 105, 108, 109, 110, 113, 114, 115, 116, 117, 118, 119, 121, 122, 123, 125, 126, 127, 128, 129, 132, 133, 134, 135, 137, 138, 139, 141, 142, 143, 144, 146, 147, 148, 149, 150, 151, 153, 154, 155, 156, 158, 159, 161, 163, 164, 165, 167, 168, 170, 172, 174, 175, 176, 178, 180, 181, 184, 186, 187, 188, 190, 191, 192, 193, 196, 197, 199, 202, 204, 205, 206, 207, 208, 209, 210, 211, 214, 215, 216, 218, 219, 220, 221, 222, 224, 229, 230, 231, 232, 234, 237, 238, 240, 241, 243, 245, 246, 247, 248, 249, 250, 251, 252, 254, 255, 256, 257, 258, 260, 262, 263, 264, 265, 271, 272, 274, 277, 278, 280, 281, 282, 283, 285, 286, 288, 290, 291, 294, 297, 299, 301, 302, 303, 305, 306, 307, 309, 311, 312, 313, 314, 316, 319, 321, 322, 325, 327, 328, 329, 331, 333, 334, 335, 338, 339, 342, 343, 344, 345, 346, 347, 348, 350, 351, 352, 354, 356, 357, 358, 360, 363, 364, 365, 366, 368, 369, 370, 372, 373, 375, 376, 377, 378, 379, 381, 383, 385, 386, 387, 388, 389, 390, 391, 393, 394, 397, 398, 399, 400, 402, 403, 404, 405, 406, 407, 408, 410, 412, 413, 414, 416, 417, 418, 419, 421, 422, 423, 424, 425, 428, 429, 432, 433, 434, 436, 437, 439, 440, 441, 442, 444, 445, 446, 447, 448, 449, 450, 456, 457, 458, 459, 460, 461, 462, 463, 464, 468, 469, 470, 471, 472, 473, 475, 477, 480, 482, 483, 484, 485, 486, 488, 490, 491, 492, 493, 494, 495, 496, 498, 500, 502, 503, 505, 506, 508, 509, 512, 513, 515, 517, 518, 520, 521, 522, 524, 525, 526, 527, 528, 529, 530, 531, 533, 534, 539, 540, 541, 542, 545, 546, 547, 548, 551, 552, 553, 554, 555, 557, 558, 559, 560, 561, 562, 563, 564, 568, 569, 570, 571, 573, 574, 575, 576, 577, 578, 579, 580, 581, 584, 585, 587, 588, 589, 590, 592, 595, 596, 598, 599, 600, 601, 602, 603, 605, 606, 608, 610, 612, 613, 614, 615, 616, 617, 620, 622, 623, 624, 625, 626, 629, 632, 633, 634, 635, 636, 637, 640, 641, 643, 644, 646, 647, 648, 651, 652, 653, 654, 655, 656, 658, 661, 663, 664, 666, 667, 669, 671, 673, 674, 676, 677, 679, 681, 682, 683, 684, 685, 687, 688, 690, 691, 693, 695, 696, 697, 700, 701, 702, 703, 704, 705, 707, 709, 710, 711, 712, 713, 714, 715, 716, 720, 722, 723, 725, 726, 727, 728, 729, 730, 731, 733, 734, 735, 736, 737, 739, 740, 742, 744, 745, 746, 747, 748, 749, 750, 751, 752, 754, 756, 760, 761, 762, 763, 764, 765, 768, 770, 771, 772, 773, 774, 777, 780, 781, 782, 784, 785, 787, 788, 790, 791, 792, 795, 797, 799, 802, 803, 806, 807, 808, 809, 811, 813, 814, 815, 816, 819, 820, 822, 823, 824, 825, 826, 827, 830, 831, 832, 833, 835, 836, 838, 839, 840, 841, 842, 844, 846, 847, 848, 849, 850, 852, 853, 855, 856, 857, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 871, 875, 876, 877, 878, 879, 881, 883, 884, 885, 886, 888, 890, 891, 892, 893, 894, 895, 896, 897, 898, 900, 901, 903, 904, 905, 906, 907, 909, 910, 911, 912, 913, 914, 915, 917, 918, 920, 921, 922, 923, 924, 925, 927, 928, 929, 930, 931, 932, 933, 934, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 951, 953, 954, 955, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 989, 990, 991, 992, 993, 995, 996, 997, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010]

In [18]:
pd.concat([pd_df, opd_df], axis=1)

,id,age,job,marital,education,balance,housing,loan,default,id,gender
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no,1.0,women
1,2,25.0,technician,married,secondary,517,no,no,no,2.0,women
2,3,36.0,technician,single,secondary,1044,yes,no,no,3.0,man
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no,5.0,man
4,5,27.0,management,married,tertiary,145,no,no,no,6.0,man
...,...,...,...,...,...,...,...,...,...,...,...
995,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no,NaN,NaN
996,997,58.0,management,married,tertiary,1271,yes,no,no,NaN,NaN
997,998,31.0,services,single,secondary,297,no,no,no,NaN,NaN
998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no,NaN,NaN
999,1000,23.0,blue-collar,single,secondary,780,yes,no,no,NaN,NaN

In [19]:
pd_df.merge(opd_df)

,id,age,job,marital,education,balance,housing,loan,default,gender
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no,women
1,2,25.0,technician,married,secondary,517,no,no,no,women
2,3,36.0,technician,single,secondary,1044,yes,no,no,man
3,5,27.0,management,married,tertiary,145,no,no,no,man
4,6,45.0,unemployed,divorced,primary,11,no,no,yes,man
...,...,...,...,...,...,...,...,...,...,...
695,995,NaN,management,married,secondary,106,no,no,no,women
696,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no,man
697,997,58.0,management,married,tertiary,1271,yes,no,no,man
698,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no,women
699,1000,23.0,blue-collar,single,secondary,780,yes,no,no,man

In [20]:
pd.merge(left=pd_df, right=opd_df, on='id', how='inner')

,id,age,job,marital,education,balance,housing,loan,default,gender
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no,women
1,2,25.0,technician,married,secondary,517,no,no,no,women
2,3,36.0,technician,single,secondary,1044,yes,no,no,man
3,5,27.0,management,married,tertiary,145,no,no,no,man
4,6,45.0,unemployed,divorced,primary,11,no,no,yes,man
...,...,...,...,...,...,...,...,...,...,...
695,995,NaN,management,married,secondary,106,no,no,no,women
696,996,41.0,entrepreneur,married,secondary,-1882,yes,no,no,man
697,997,58.0,management,married,tertiary,1271,yes,no,no,man
698,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no,women
699,1000,23.0,blue-collar,single,secondary,780,yes,no,no,man

In [21]:
pd.merge(left=pd_df, right=opd_df, on='id', how='outer')

,id,age,job,marital,education,balance,housing,loan,default,gender
0,1,26.0,unemployed,married,tertiary,454.0,yes,yes,no,women
1,2,25.0,technician,married,secondary,517.0,no,no,no,women
2,3,36.0,technician,single,secondary,1044.0,yes,no,no,man
3,4,45.0,blue-collar,married,secondary,146.0,yes,yes,no,NaN
4,5,27.0,management,married,tertiary,145.0,no,no,no,man
...,...,...,...,...,...,...,...,...,...,...
1005,1006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
1006,1007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,man
1007,1008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,man
1008,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women
1009,1010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,women

In [35]:
new_client_df =pd.DataFrame( [{'id': 1020,
                              'age': 40,
                              'job': 'unknown',
                              'marital': 'married',
                              'education': 'secondary',
                              'balance': 0,
                              'housing': 'yes',
                              'loan': 'yes',
                              'default': 'yes'}])
new_client_df

     id  age      job  marital  education  balance housing loan default
0  1020   40  unknown  married  secondary        0     yes  yes     yes

In [36]:
new_client_df = new_client_df.set_index('id')
new_client_df

      age      job  marital  education  balance housing loan default
id
1020   40  unknown  married  secondary        0     yes  yes     yes

In [54]:
pd_df = pd.read_csv('12.5.Data/partner_data.csv')
pd_df.head()

   id   age          job  marital  education  balance housing loan default
0   1  26.0   unemployed  married   tertiary      454     yes  yes      no
1   2  25.0   technician  married  secondary      517      no   no      no
2   3  36.0   technician   single  secondary     1044     yes   no      no
3   4  45.0  blue-collar  married  secondary      146     yes  yes      no
4   5  27.0   management  married   tertiary      145      no   no      no

In [46]:
pd_df = pd_df.set_index('id')
pd_df

       age           job  marital  education  balance housing loan default
id
1     26.0    unemployed  married   tertiary      454     yes  yes      no
2     25.0    technician  married  secondary      517      no   no      no
3     36.0    technician   single  secondary     1044     yes   no      no
4     45.0   blue-collar  married  secondary      146     yes  yes      no
5     27.0    management  married   tertiary      145      no   no      no
...    ...           ...      ...        ...      ...     ...  ...     ...
996   41.0  entrepreneur  married  secondary    -1882     yes   no      no
997   58.0    management  married   tertiary     1271     yes   no      no
998   31.0      services   single  secondary      297      no   no      no
999   31.0  entrepreneur      NaN   tertiary      312      no   no      no
1000  23.0   blue-collar   single  secondary      780     yes   no      no

[1000 rows x 8 columns]

In [48]:
# появляются новые столбцы
pd.merge(left = pd_df, right = new_client_df, on='id', how='outer')

,age_x,job_x,marital_x,education_x,balance_x,housing_x,loan_x,default_x,age_y,job_y,marital_y,education_y,balance_y,housing_y,loan_y,default_y
id,,,,,,,,,,,,,,,,
1,26.0,unemployed,married,tertiary,454.0,yes,yes,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,25.0,technician,married,secondary,517.0,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,36.0,technician,single,secondary,1044.0,yes,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,45.0,blue-collar,married,secondary,146.0,yes,yes,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,27.0,management,married,tertiary,145.0,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,58.0,management,married,tertiary,1271.0,yes,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,31.0,services,single,secondary,297.0,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,31.0,entrepreneur,NaN,tertiary,312.0,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,23.0,blue-collar,single,secondary,780.0,yes,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,unknown,married,secondary,0.0,yes,yes,yes

In [87]:
# индекс не сохраняется
pd.merge(left = pd_df, right = new_client_df, how='outer')

,id,age,job,marital,education,balance,housing,loan,default
0,1.0,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2.0,25.0,technician,married,secondary,517,no,no,no
2,3.0,36.0,technician,single,secondary,1044,yes,no,no
3,4.0,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5.0,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
996,997.0,58.0,management,married,tertiary,1271,yes,no,no
997,998.0,31.0,services,single,secondary,297,no,no,no
998,999.0,31.0,entrepreneur,NaN,tertiary,312,no,no,no
999,1000.0,23.0,blue-collar,single,secondary,780,yes,no,no
1000,NaN,40.0,unknown,married,secondary,0,yes,yes,yes

In [88]:
pd_df.append(new_client_obj, ignore_index=True)

<ipython-input-88-6601a45fd027>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pd_df.append(new_client_obj, ignore_index=True)

,id,age,job,marital,education,balance,housing,loan,default
0,1,26.0,unemployed,married,tertiary,454,yes,yes,no
1,2,25.0,technician,married,secondary,517,no,no,no
2,3,36.0,technician,single,secondary,1044,yes,no,no
3,4,45.0,blue-collar,married,secondary,146,yes,yes,no
4,5,27.0,management,married,tertiary,145,no,no,no
...,...,...,...,...,...,...,...,...,...
996,997,58.0,management,married,tertiary,1271,yes,no,no
997,998,31.0,services,single,secondary,297,no,no,no
998,999,31.0,entrepreneur,NaN,tertiary,312,no,no,no
999,1000,23.0,blue-collar,single,secondary,780,yes,no,no
1000,1020,40.0,unknown,married,secondary,0,yes,yes,yes

# Разные эксперименты

In [125]:
df1 = pd.DataFrame(
       {
           "A": ["A0", "A1", "A2", "A3"],
           "B": ["B0", "B1", "B2", "B3"],
           "C": ["C0", "C1", "C2", "C3"],
           "D": ["D0", "D1", "D2", "D3"],
       },
       index=[1, 2, 3, 4],
   )
df1

    A   B   C   D
1  A0  B0  C0  D0
2  A1  B1  C1  D1
3  A2  B2  C2  D2
4  A3  B3  C3  D3

In [126]:
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[5, 6, 7,8],
)
df2

    A   B   C   D
5  A4  B4  C4  D4
6  A5  B5  C5  D5
7  A6  B6  C6  D6
8  A7  B7  C7  D7

In [127]:
df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[9, 10, 11, 12],
)
df3

      A    B    C    D
9    A8   B8   C8   D8
10   A9   B9   C9   D9
11  A10  B10  C10  D10
12  A11  B11  C11  D11

In [71]:
pd.merge(left = df1, right = df2, how='outer')

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [74]:
pd.concat([df1,df2])

    A   B   C   D
1  A0  B0  C0  D0
2  A1  B1  C1  D1
3  A2  B2  C2  D2
4  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [73]:
pd.concat([df1,df2],axis = 1)

     A    B    C    D    A    B    C    D
1   A0   B0   C0   D0  NaN  NaN  NaN  NaN
2   A1   B1   C1   D1  NaN  NaN  NaN  NaN
3   A2   B2   C2   D2  NaN  NaN  NaN  NaN
4   A3   B3   C3   D3   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

https://newtechaudit.ru/pandas-merge-join-concatenate/

In [113]:
df11 = pd.DataFrame({'A': ['5', '87', '42', '43'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                     'D': ['D0', 'D1', 'D2', 'D3']})

In [114]:
df12 = pd.DataFrame({'A1': ['43', '3', '80', '5'],
                     'B1': ['B0', 'B1', 'B5', 'B3'],
                     'C1': ['C4', 'C5', 'C6', 'C7'],
                     'D1': ['D4', 'D5', 'D6', 'D7']})

In [115]:
pd.concat([df11,df12],axis = 1)

    A   B   C   D  A1  B1  C1  D1
0   5  B0  C0  D0  43  B0  C4  D4
1  87  B1  C1  D1   3  B1  C5  D5
2  42  B2  C2  D2  80  B5  C6  D6
3  43  B3  C3  D3   5  B3  C7  D7

In [116]:
pd.concat([df11,df12])

     A    B    C    D   A1   B1   C1   D1
0    5   B0   C0   D0  NaN  NaN  NaN  NaN
1   87   B1   C1   D1  NaN  NaN  NaN  NaN
2   42   B2   C2   D2  NaN  NaN  NaN  NaN
3   43   B3   C3   D3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN   43   B0   C4   D4
1  NaN  NaN  NaN  NaN    3   B1   C5   D5
2  NaN  NaN  NaN  NaN   80   B5   C6   D6
3  NaN  NaN  NaN  NaN    5   B3   C7   D7

In [117]:
df11.join(df12)

    A   B   C   D  A1  B1  C1  D1
0   5  B0  C0  D0  43  B0  C4  D4
1  87  B1  C1  D1   3  B1  C5  D5
2  42  B2  C2  D2  80  B5  C6  D6
3  43  B3  C3  D3   5  B3  C7  D7

In [118]:
# пересечение таблиц по равным элементам в столбцах B и B1
df11.merge(df12, left_on='B', right_on='B1', how='inner')

    A   B   C   D  A1  B1  C1  D1
0   5  B0  C0  D0  43  B0  C4  D4
1  87  B1  C1  D1   3  B1  C5  D5
2  43  B3  C3  D3   5  B3  C7  D7

In [119]:
pd.merge(left = df11, right = df12, left_on='B', right_on='B1', how='inner')

    A   B   C   D  A1  B1  C1  D1
0   5  B0  C0  D0  43  B0  C4  D4
1  87  B1  C1  D1   3  B1  C5  D5
2  43  B3  C3  D3   5  B3  C7  D7

In [122]:
# объединение таблиц по элементам в столбцах B и B1
df11.merge(df12, left_on='B', right_on='B1', how='outer')

     A    B    C    D   A1   B1   C1   D1
0    5   B0   C0   D0   43   B0   C4   D4
1   87   B1   C1   D1    3   B1   C5   D5
2   42   B2   C2   D2  NaN  NaN  NaN  NaN
3   43   B3   C3   D3    5   B3   C7   D7
4  NaN  NaN  NaN  NaN   80   B5   C6   D6

In [123]:
pd.merge(left = df11, right = df12, left_on='B', right_on='B1', how='outer')

     A    B    C    D   A1   B1   C1   D1
0    5   B0   C0   D0   43   B0   C4   D4
1   87   B1   C1   D1    3   B1   C5   D5
2   42   B2   C2   D2  NaN  NaN  NaN  NaN
3   43   B3   C3   D3    5   B3   C7   D7
4  NaN  NaN  NaN  NaN   80   B5   C6   D6

In [128]:
df1

    A   B   C   D
1  A0  B0  C0  D0
2  A1  B1  C1  D1
3  A2  B2  C2  D2
4  A3  B3  C3  D3

In [129]:
df11

    A   B   C   D
0   5  B0  C0  D0
1  87  B1  C1  D1
2  42  B2  C2  D2
3  43  B3  C3  D3

In [131]:
res_df = pd.concat([df1,df11])
res_df

    A   B   C   D
1  A0  B0  C0  D0
2  A1  B1  C1  D1
3  A2  B2  C2  D2
4  A3  B3  C3  D3
0   5  B0  C0  D0
1  87  B1  C1  D1
2  42  B2  C2  D2
3  43  B3  C3  D3

In [134]:
res_df.loc[1,:]

    A   B   C   D
1  A0  B0  C0  D0
1  87  B1  C1  D1